# Generated by Django 3.2.9 on 2021-11-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team', models.CharField(max_length=50)),
                ('second_team', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
